development:
  adapter: postgresql
  host: localhost
  database: whiteboard_development

test:
  adapter: postgresql
  host: localhost
  database: whiteboard_test

production:
  adapter: postgresql
  host: localhost
  database: whiteboard_production